# Country comparison {#country-comparison}

## Discernment by country

```{r, echo=FALSE}
ggplot(accuracy_effect %>% 
         group_by(country_mapcompatible) %>% 
         summarise(yi = mean(yi), 
                   n_effect = n_distinct(observation_id)) %>% 
         mutate(country = fct_reorder(country_mapcompatible, desc(yi))), 
       aes(x = country, y = yi, color = country)) +
  geom_pointrange(aes(ymin = 0, ymax = yi), size = 0.2) +
  scale_color_viridis_d(option = "rocket", begin = 0.65, end = 1) +
  # Turn off the legend since the title shows what the orange is
  guides(color = "none") +
  labs(x = NULL, y = "Average discernment estimate (SMCC)") +
  scale_y_continuous(limits = c(0, 2.5)) +
  coord_flip() +
  # add labels for effects
  geom_text(aes(label = paste0("n= ", n_effect)), hjust = -0.5, color = "black") +  # Add geom_text for n_effect labels
  plot_theme
```

```{r, echo=FALSE}
plot_map(fill = "discernment")
```

## Response bias by country

```{r, echo=FALSE}
ggplot(error_effect %>% 
         group_by(country_mapcompatible) %>% 
         summarise(yi = mean(yi), 
                   n_effect = n_distinct(observation_id)) %>% 
         mutate(country = fct_reorder(country_mapcompatible, desc(yi)), 
                # for plotting labels later
                h_adjust = ifelse(yi < 0, -0.1, 0.1)), 
       aes(x = country, y = yi, color = yi)) +
  geom_pointrange(aes(ymin = 0, ymax = yi), size = 0.2) +
  scale_color_gradient2(low = "#2C7BB6", mid = "grey", high = "#D7191C",
                         midpoint = 0, na.value = "white") +
  # Turn off the legend since the title shows what the orange is
  guides(color = "none") +
  labs(x = NULL, y = "Average response bias estimate (SMCC)") +
  coord_flip() +
  # add labels for effects
  geom_text(aes(y = yi + h_adjust, label = paste0("n= ", n_effect)),  color = "black") +  # Add geom_text for n_effect labels
  plot_theme
```

```{r, echo=FALSE}
plot_map(fill = "response bias", data = error_effect)
```





